export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const RPODUCT_LIST_SUCCESS = "RPODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const RPODUCT_DETAILS_SUCCESS = "RPODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
